version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    environment:
      - FLASK_ENV=development
    develop:
      # Create a `watch` configuration to update the app
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

volumes:
  sqlite_data: